### ISSUE TITLE
Broadcasting Fails on Android 9.0

### ISSUE THREAD

**Issue by kir12** [googlesamples/android-BluetoothAdvertisements#14]
I am testing this app on Android 9.0 and upon hitting the Broadcast Switch I get the below error:

```
2019-06-11 18:50:19.661 28219-28219/com.example.android.bluetoothadvertisements E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.bluetoothadvertisements, PID: 28219
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

How would I go about resolving this problem?

**Comment by kir12** [comment]
On an unrelated note, the app also works for Android SDK 24 (Nougat) despite the minimum requirements being Android SDK 27 (Oreo 8.1)

**Comment by kir12** [comment]
UPDATE: I have fixed the original issue using a solution posted from [this issue](https://github.com/googlesamples/android-BluetoothAdvertisements/issues/10). That being said, I still don't know to what extent the app works on Android Nougat -- the app starts up properly and appears to work on the front end, but fails to both advertise and recieve from another phone. (running Android Pie) What's the specific component inside the project that explicitly requires Android Oreo and above?
